s=['peak','seak','acid','aged','able','also','beak','army','blow','bite','calm','care','coat','crew','deal', 'disk','earn','duty','evil','fast','fear','find','fact','fine'
,'flow','gain','goal','hard','heat','give','girl', 'gear','gold','grey','golf','glad','grow','half','hair','hear','hang','head','hate','help','high','hero','holy', 'host','hurt'
,'hunt','huge','hole','hire','inch','into','iron','item','jack','jane','jean','join','jump','jury', 'just','kent','kept','kind','king','know','lack','lady','laid','lazy','lake'
,'land','lane','last','late','lead', 'left','life','lift','like','line','link','list','live','load','loan','lawn','lock','logo','long','lord','lose', 'lost','love','luck','made'
,'male','mail','main','make','many','meal','mean','meat','menu','mike','milk','mile', 'mind','mine','mode','more','most','move','much','must','name','navy','near','neck','news'
,'next','nice','nick', 'nose','note','okay','once','only','onto','open','oral','over','pace','pack','page','paid','pain','pair','palm', 'park','part','past','path','pick','pink','plan'
,'play','plot','plug','plus','port','post','pure','push','rash', 'race','rail','rain','rank','rate','read','real','rear','rely','rent','rest','rice','rich','ride','ring','rise', 'risk'
,'hope','road','rock','role','rose','rule','rush','ruth','safe','said','sack','save','sale','salt','sane', 'same','sand','seat','soul','send','self','sent','sept','ship','shop','shot'
,'show','shut','sick','side','sign', 'site','size','skin','slow','slip','slow','snow','soft','soil','sold','sole','some','song','sort','spot','star', 'stay','stop','such','suit','sure'
,'take','tale','tail','talk','tank','tape','task','team','tech','tent','tend', 'term','then','them','than','they','thin','this','thus','time','tiny','told','tone','tony','tour','town'
,'trip', 'trap','true','tune','turn','twin','type','unit','upon','used','user','very','vary','vast','wise','view','vice', 'vote','vase','wage','wait','wake','walk','want','word','ward'
,'warm','wash','wave','ways','weak','wear','went', 'west','what','when','whom','wide','wild','wife','wind','wine','wing','wire','wish','with','wore','work','year', 'yeah','yard','your'
,'zero','zone','fire','area','away','back','band','bank','base','bath','bear','beat','belt', 'best','bird','blue','boat','body','bond','bone','born','both','bowl','bulk','burn','bush'
,'busy','came','camp', 'card','case','cash','cast','chat','chip','city','club','coal','code','cold','come','cope','copy','core','cost', 'crop','dark','date','days','dawn','dean','dear'
,'debt','deny','desk','dial','duck','diet','disc','does','done', 'dose','down','draw','drop','drew','drug','dual','duke','dust','each','exit','east','easy','face','fail','fare', 'farm'
,'fate','felt','file','film','fire','firm','fish','five','flat','ford','form','foam','fort','four','from', 'fuel','fund', 'sail', 'ping', 'kill', "atom", "mike"]

